In [1]:
#importing dependencies
import time
import numpy as np
import pandas as pd
from nltk.corpus import stopwords
from bs4 import BeautifulSoup  
import re

In [2]:
#Reading the Data
data = pd.read_pickle('./data/data_clean/Data.pik')

In [3]:
X = data['Corpus']
y = data['Label']

In [4]:
#Stop Words
stops = set(stopwords.words("Portuguese"))
print(stops)

{'esteve', 'quando', 'fossem', 'houverem', 'pelas', 'elas', 'estes', 'os', 'tivéssemos', 'tivesse', 'tem', 'era', 'suas', 'aqueles', 'estamos', 'minha', 'foi', 'tua', 'em', 'mais', 'não', 'estiverem', 'houverão', 'foram', 'na', 'nossas', 'serei', 'sua', 'sou', 'houvesse', 'tenham', 'sejam', 'tivermos', 'deles', 'numa', 'tinha', 'seus', 'tive', 'temos', 'nas', 'no', 'essas', 'tivera', 'hão', 'nosso', 'quem', 'e', 'nossos', 'estávamos', 'houve', 'teríamos', 'há', 'dela', 'aquele', 'houvemos', 'for', 'hajamos', 'esse', 'tu', 'seriam', 'havemos', 'eles', 'seja', 'à', 'até', 'seremos', 'tiver', 'da', 'tivessem', 'ela', 'tenho', 'que', 'ao', 'mas', 'entre', 'nem', 'estivesse', 'de', 'um', 'estivera', 'fôssemos', 'está', 'as', 'estavam', 'hei', 'houvéssemos', 'pelos', 'eram', 'houverei', 'tenhamos', 'isso', 'houvessem', 'num', 'teriam', 'houveram', 'seu', 'pela', 'eu', 'sejamos', 'sem', 'vos', 'teve', 'seria', 'tivemos', 'para', 'tínhamos', 'tiveram', 'estivermos', 'meus', 'estiveram', 'teu',

In [5]:
def review_to_words( raw_review ):
    # Function to convert a raw review to a string of words
    # The input is a single string (a raw movie review), and 
    # the output is a single string
    #
    # 1. Remove HTML
    review_text = BeautifulSoup(raw_review,"lxml").get_text() 
    #
    # 2. Remove non-letters        
    letters_only = re.sub("[^a-zA-Z]", " ", review_text) 
    #
    # 3. Convert to lower case, split into individual words
    words = letters_only.lower().split()                             
    #
    # 4. In Python, searching a set is much faster than searching
    #   a list, so convert the stop words to a set
    stops = set(stopwords.words("Portuguese"))                  
    # 
    # 5. Remove stop words
    meaningful_words = [w for w in words if not w in stops]   
    #
    # 6. Join the words back into one string separated by space, 
    # and return the result.
    return( " ".join( meaningful_words ))  

In [6]:
clean_document = review_to_words( X[0] )
print(clean_document)

tivit terceiriza processos servi tecnologia s cnpj mf nire edital segunda convoca assembleias gerais extraordin riasficam senhores acionistas tivit terceiriza processos servi ose tecnologia s convocados reunir assembleias geraisextraordin rias companhia ser realizadas segunda convoca julho sede social companhia localizada avenidaprefeito carlos ferreira lopes n cidade mogi cruzes estado s paulo s hs hs seguintes ordens dia assembleia geral extraordin ria ser realizada s hs aprova proposta plano op compra es emiss oda companhia termos minuta disponibilizada acionistas aconseq ente altera artigos item h estatuto social dacompanhia b aumento valor global remunera administradores assembleia geral extraordin ria ser realizada s hs aprova sa companhia novo mercado segmento especial denegocia bm fbovespa b sele acionistas n controladores companhia detentores dea es circula companhia conforme definido regulamento novomercado dentre seguintes institui es especializadas sercontratada elabora ter

In [7]:
# Get the number of documents based on the dataframe column size
num_documents = X.size

# Initialize an empty list to hold the clean Documents
clean_train_corpus = []

# Loop over each review; create an index i that goes from 0 to the length of documents 
for i in range( 0, num_documents ):
    # Call our function for each one, and add the result to the list of clena documents
     clean_train_corpus.append( review_to_words( X[i] ) )

In [93]:
print("Creating the bag of words...\n")
from sklearn.feature_extraction.text import CountVectorizer

# Initialize the "CountVectorizer" object, which is scikit-learn's
# bag of words tool.  
vectorizer = CountVectorizer(analyzer = "word",   \
                             tokenizer = None,    \
                             preprocessor = None, \
                             stop_words = None,   \
                             max_features = 10000) 

# fit_transform() does two functions: First, it fits the model
# and learns the vocabulary; second, it transforms our training data
# into feature vectors. The input to fit_transform should be a list of 
# strings.
train_data_features = vectorizer.fit_transform(clean_train_corpus)

# Numpy arrays are easy to work with, so convert the result to an 
# array
train_data_features = train_data_features.toarray()

Creating the bag of words...



In [94]:
train_data_features.shape

(6837, 10000)

In [95]:
# Take a look at the words in the vocabulary
vocab = vectorizer.get_feature_names()
print(vocab)

['aa', 'aaa', 'aadministra', 'aapl', 'aarrttiiggoo', 'ab', 'abaixo', 'abalancete', 'abandono', 'abastecimento', 'abate', 'abatimentos', 'abbett', 'abbott', 'abc', 'aberdeen', 'aberta', 'abertas', 'aberto', 'abertos', 'abertura', 'abilio', 'abl', 'abn', 'abono', 'abordagem', 'abordando', 'abordar', 'abott', 'about', 'abr', 'abrang', 'abrange', 'abrangem', 'abrangendo', 'abrangente', 'abrangentes', 'abrangentespatrim', 'abranger', 'abrangidas', 'abrasce', 'abreu', 'abril', 'abrilpar', 'abrir', 'abriu', 'absoluta', 'absor', 'absorver', 'absorvido', 'absorvidos', 'absten', 'abster', 'abstiveram', 'abu', 'abyara', 'ac', 'acabados', 'acabou', 'acad', 'acadian', 'acarretando', 'acarretar', 'acarretaria', 'acatar', 'acautelar', 'acc', 'accenture', 'acciona', 'acciones', 'accionistas', 'accounting', 'aceit', 'aceita', 'aceitado', 'aceitantes', 'aceitar', 'aceitas', 'aceite', 'aceito', 'aceitos', 'acelera', 'acelerar', 'acerca', 'acervo', 'acess', 'acessada', 'acessado', 'acessar', 'acesse', 'ac

In [96]:
import numpy as np

# Sum up the counts of each vocabulary word
dist = np.sum(train_data_features, axis=0)

# For each, print the vocabulary word and the number of times it 
# appears in the training set
for tag, count in zip(vocab, dist):
    print(count, tag)

1067 aa
143 aaa
149 aadministra
76 aapl
298 aarrttiiggoo
197 ab
14644 abaixo
89 abalancete
94 abandono
332 abastecimento
262 abate
97 abatimentos
117 abbett
107 abbott
322 abc
127 aberdeen
8722 aberta
1617 abertas
2365 aberto
221 abertos
1333 abertura
77 abilio
408 abl
271 abn
130 abono
384 abordagem
361 abordando
140 abordar
86 abott
85 about
2294 abr
114 abrang
247 abrange
112 abrangem
195 abrangendo
572 abrangente
607 abrangentes
73 abrangentespatrim
107 abranger
243 abrangidas
84 abrasce
530 abreu
12353 abril
199 abrilpar
317 abrir
73 abriu
689 absoluta
263 absor
98 absorver
73 absorvido
66 absorvidos
783 absten
464 abster
88 abstiveram
94 abu
106 abyara
472 ac
124 acabados
64 acabou
281 acad
97 acadian
84 acarretando
571 acarretar
157 acarretaria
99 acatar
135 acautelar
150 acc
66 accenture
134 acciona
108 acciones
79 accionistas
829 accounting
189 aceit
2355 aceita
128 aceitado
192 aceitantes
703 aceitar
154 aceitas
156 aceite
156 aceito
227 aceitos
184 acelera
72 acelerar
2848 a

In [97]:
#Train Test Split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = \
train_test_split(train_data_features, y, test_size=0.2,random_state=101)

## Randon Forest Model

In [98]:
from sklearn.ensemble import RandomForestClassifier
Rf_model = RandomForestClassifier(n_estimators=300, n_jobs=-1)

In [99]:
Rf_model.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=300, n_jobs=-1, oob_score=False,
            random_state=None, verbose=0, warm_start=False)

In [100]:
y_pred = Rf_model.predict(X_test)

In [101]:
from sklearn.metrics import classification_report, confusion_matrix
print (classification_report(y_test, y_pred))
print (confusion_matrix(y_test, y_pred))

                                  precision    recall  f1-score   support

        Cancelamento de Registro       0.80      0.43      0.56        56
              Controle Acionario       0.85      0.41      0.55        27
          Direito de Preferencia       0.69      0.31      0.43        65
                       Dividendo       0.94      0.99      0.97       783
                  Oferta Publica       0.76      0.88      0.81       190
Pedido de Recuperação Judicial       0.98      0.82      0.89        72
                    Subscrição       0.79      0.85      0.82       175

                     avg / total       0.88      0.88      0.87      1368

[[ 24   0   0   3  27   0   2]
 [  0  11   0   6   8   0   2]
 [  0   0  20   6   7   0  32]
 [  0   0   0 779   1   1   2]
 [  6   1   2  12 167   0   2]
 [  0   0   0   9   4  59   0]
 [  0   1   7  12   6   0 149]]


## Naive Bayes Model

In [14]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import GridSearchCV
parameters = {'alpha' : (1, 1e-2,1e-3,1e-4, 1e-5, 1e-6, 1e-7, 1e-8, 1e-9, 1e-10)}

In [15]:
gs_bow_model = GridSearchCV(MultinomialNB(), parameters, n_jobs=1,cv=10)
gs_bow_model.fit(X_train, y_train)

GridSearchCV(cv=10, error_score='raise',
       estimator=MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True),
       fit_params={}, iid=True, n_jobs=1,
       param_grid={'alpha': (1, 0.01, 0.001, 0.0001, 1e-05, 1e-06, 1e-07, 1e-08, 1e-09, 1e-10)},
       pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
       scoring=None, verbose=0)

In [16]:
gs_bow_model.best_score_

0.82025964527335893

In [17]:
for param_name in sorted(parameters.keys()):
    print("%s: %r" % (param_name, gs_bow_model.best_params_[param_name]))

alpha: 1e-10


In [18]:
y_pred = gs_bow_model.predict(X_test)

In [19]:
from sklearn.metrics import classification_report, confusion_matrix
print (classification_report(y_test, y_pred))
print (confusion_matrix(y_test, y_pred))

                                  precision    recall  f1-score   support

        Cancelamento de Registro       0.58      0.54      0.56        56
              Controle Acionario       0.75      0.22      0.34        27
          Direito de Preferencia       0.55      0.35      0.43        65
                       Dividendo       0.93      0.94      0.94       783
                  Oferta Publica       0.77      0.71      0.74       190
Pedido de Recuperação Judicial       0.88      0.69      0.78        72
                    Subscrição       0.61      0.83      0.71       175

                     avg / total       0.83      0.83      0.82      1368

[[ 30   1   0   9  10   0   6]
 [  1   6   1   8   7   3   1]
 [  0   0  23   6   4   1  31]
 [  1   0   1 739   7   0  35]
 [ 20   1   5  14 135   2  13]
 [  0   0   2  10   4  50   6]
 [  0   0  10   9   9   1 146]]


## Cross Validation

In [73]:
from sklearn.model_selection import cross_val_score
cross_RF_Model= cross_val_score(RandomForestClassifier(n_estimators=300), X_train, y_train, cv=10, n_jobs=-1)

In [74]:
cross_RF_Model

array([ 0.86545455,  0.89781022,  0.88138686,  0.87043796,  0.87956204,
        0.88868613,  0.87728938,  0.88256881,  0.86580882,  0.875     ])